#Clock Interface
set_property PACKAGE_PIN F22 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN T18 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PULLUP true [get_ports rst_n]


#LED Top Interface
#set_property PACKAGE_PIN B25 [get_ports {led_data_top[0]}]
#set_property PACKAGE_PIN B26 [get_ports {led_data_top[1]}]
#set_property PACKAGE_PIN C26 [get_ports {led_data_top[2]}]
#set_property PACKAGE_PIN D26 [get_ports {led_data_top[3]}]
#set_property PACKAGE_PIN E26 [get_ports {led_data_top[4]}]
#set_property PACKAGE_PIN G26 [get_ports {led_data_top[5]}]
#set_property PACKAGE_PIN H26 [get_ports {led_data_top[6]}]
#set_property PACKAGE_PIN J26 [get_ports {led_data_top[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_data_top[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_data_top[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_data_top[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_data_top[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_data_top[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_data_top[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_data_top[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {led_data_top[0]}]

#key Interface
#set_property PACKAGE_PIN U2 [get_ports {key_data[0]}]
#set_property PACKAGE_PIN U1 [get_ports {key_data[1]}]
#set_property PACKAGE_PIN AF2 [get_ports {key_data[2]}]
#set_property PACKAGE_PIN AF3 [get_ports {key_data[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {key_data[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {key_data[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {key_data[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {key_data[0]}]

#Uart Interface
#set_property PACKAGE_PIN U6 [get_ports fpga_rxd]
#set_property PACKAGE_PIN U7 [get_ports fpga_txd]
#set_property IOSTANDARD LVCMOS33 [get_ports fpga_rxd]
#set_property IOSTANDARD LVCMOS33 [get_ports fpga_txd]

#HDMI Interface
set_property PACKAGE_PIN F12 [get_ports lcd_dclk] 
set_property PACKAGE_PIN A14 [get_ports lcd_de]        
set_property PACKAGE_PIN B15 [get_ports lcd_hs]        
set_property PACKAGE_PIN A15 [get_ports lcd_vs]
set_property PACKAGE_PIN J11 [get_ports lcd_red[7]]  
set_property PACKAGE_PIN J10 [get_ports lcd_red[6]]  
set_property PACKAGE_PIN H12 [get_ports lcd_red[5]]  
set_property PACKAGE_PIN H11 [get_ports lcd_red[4]]  
set_property PACKAGE_PIN G10 [get_ports lcd_red[3]]  
set_property PACKAGE_PIN G9	 [get_ports lcd_red[2]]  
set_property PACKAGE_PIN G11 [get_ports lcd_red[1]]  
set_property PACKAGE_PIN F10 [get_ports lcd_red[0]]  
set_property PACKAGE_PIN A9	 [get_ports lcd_green[7]]  
set_property PACKAGE_PIN A8	 [get_ports lcd_green[6]]  
set_property PACKAGE_PIN B10 [get_ports lcd_green[5]]  
set_property PACKAGE_PIN A10 [get_ports lcd_green[4]]  
set_property PACKAGE_PIN E11 [get_ports lcd_green[3]]  
set_property PACKAGE_PIN D11 [get_ports lcd_green[2]]  
set_property PACKAGE_PIN G12 [get_ports lcd_green[1]]   
set_property PACKAGE_PIN B12 [get_ports lcd_green[0]]   
set_property PACKAGE_PIN B11 [get_ports lcd_blue[7]]   
set_property PACKAGE_PIN A13 [get_ports lcd_blue[6]]   
set_property PACKAGE_PIN A12 [get_ports lcd_blue[5]]   
set_property PACKAGE_PIN H14 [get_ports lcd_blue[4]]   
set_property PACKAGE_PIN G14 [get_ports lcd_blue[3]]   
set_property PACKAGE_PIN F14 [get_ports lcd_blue[2]]   
set_property PACKAGE_PIN F13 [get_ports lcd_blue[1]]  
set_property PACKAGE_PIN B14 [get_ports lcd_blue[0]]        
                
set_property IOSTANDARD LVCMOS33 [get_ports lcd_dclk] 
set_property IOSTANDARD LVCMOS33 [get_ports lcd_de]        
set_property IOSTANDARD LVCMOS33 [get_ports lcd_hs]        
set_property IOSTANDARD LVCMOS33 [get_ports lcd_vs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_red[7]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_red[6]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_red[5]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_red[4]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_red[3]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_red[2]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_red[1]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_red[0]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_green[7]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_green[6]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_green[5]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_green[4]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_green[3]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_green[2]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_green[1]]   
set_property IOSTANDARD LVCMOS33 [get_ports lcd_green[0]]   
set_property IOSTANDARD LVCMOS33 [get_ports lcd_blue[7]]   
set_property IOSTANDARD LVCMOS33 [get_ports lcd_blue[6]]   
set_property IOSTANDARD LVCMOS33 [get_ports lcd_blue[5]]   
set_property IOSTANDARD LVCMOS33 [get_ports lcd_blue[4]]   
set_property IOSTANDARD LVCMOS33 [get_ports lcd_blue[3]]   
set_property IOSTANDARD LVCMOS33 [get_ports lcd_blue[2]]   
set_property IOSTANDARD LVCMOS33 [get_ports lcd_blue[1]]  
set_property IOSTANDARD LVCMOS33 [get_ports lcd_blue[0]]
