`timescale 1ns / 1ns
//****************************************VSCODE PLUG-IN**********************************//
//----------------------------------------------------------------------------------------
// IDE :                   VSCODE     
// VSCODE plug-in version: Verilog-Hdl-Format-4.3.20260413
// VSCODE plug-in author : Jiang Percy
//----------------------------------------------------------------------------------------
//****************************************Copyright (c)***********************************//
// Copyright(C)            ORI2333
// All rights reserved     
// File name:              
// Last modified Date:     2026/04/19 00:31:40
// Last Version:           V1.0
// Descriptions:           
//----------------------------------------------------------------------------------------
// Created by:             ORI2333
// Created date:           2026/04/19 00:31:40
// mail      :             ori2333.zh@gmail.com
// Version:                V1.0
// TEXT NAME:              sc1336_hdmi.sv
// PATH:                   E:\E_EngineeringWarehouse\FPGA_ISP\FPGA_ISP\sc1336_hdmi\rtl\sc1336_hdmi.sv
// Descriptions:           
//                         
//----------------------------------------------------------------------------------------
//****************************************************************************************//

module sc1336_hdmi(
    // global clock and reset
    input                               clk_50m                    ,// 50MHz
    input                               rst_n                      ,

    // DVP Interface
    output                              cmos_xclk                  ,// 27MHz or 24MHz, generated by PLL
    input                               cmos_pclk                  ,
    input                               cmos_vsync                 ,
    input                               cmos_href                  ,
    input                [   7: 0]      cmos_data                  ,

    output                              cmos_sclk                  ,
    inout                               cmos_sdat                  ,

	//DDR3 Interface (Internal)
    inout                [  31: 0]      ddr3_dq                    ,
    inout                [   3: 0]      ddr3_dqs_n                 ,
    inout                [   3: 0]      ddr3_dqs_p                 ,
    output               [   3: 0]      ddr3_dm                    ,

    output               [   0: 0]      ddr3_cs_n                  ,
    output                              ddr3_reset_n               ,
	
    output               [   0: 0]      ddr3_ck_p                  ,
    output               [   0: 0]      ddr3_ck_n                  ,
    output               [   0: 0]      ddr3_cke                   ,
	
    output                              ddr3_ras_n                 ,
    output                              ddr3_cas_n                 ,
    output                              ddr3_we_n                  ,
    output               [   0: 0]      ddr3_odt                   ,
	
    output               [  14: 0]      ddr3_addr                  ,
    output               [   2: 0]      ddr3_ba                    ,

    //lcd interface
    output                              lcd_dclk                   ,// 720P@60FPS 74.25MHz
    output                              lcd_hs                     ,
    output                              lcd_vs                     ,
    output                              lcd_de                     ,

    output               [   7: 0]      lcd_red                    ,
    output               [   7: 0]      lcd_green                  ,
    output               [   7: 0]      lcd_blue                    
);
// ----------------------------------------------------------------------------------------
// clock control
wire                           clk_ctrl                   ;// 100MHz
wire                           clk_video                  ;// 74.25MHz
wire                           clk_cmos                   ;// 24MHz
wire                           clk_ddr_ref                ;// 200MHz
wire                           clk_ila                    ;// 100MHz
wire                           clk_spare                  ;// 50MHz
wire                           sys_rst_n                  ;
wire                           cmos_sdat_in               ;
wire                           cmos_sdat_out              ;
wire                           cmos_sdat_oe               ;

sys_clk_ctrl#(
    .SYS_DELAY_TOP                      (24'd2500_000              ) // ~50ms delay @50MHz
)u_sys_clk_ctrl(
    // Clock and reset inputs
    .clk_in                             (clk_50m                   ),
    .ext_rst_n                          (rst_n                     ),
    // Clock and reset outputs
    .clk_out                            (                          ),// 100Mhz
    .clk_ctrl                           (clk_ctrl                  ),// 100MHz
    .clk_video                          (clk_video                 ),// 74.25MHz
    .clk_cmos                           (clk_cmos                  ),// 24MHz
    .clk_ddr_ref                        (clk_ddr_ref               ),// 200MHz
    .clk_ila                            (clk_ila                   ),// 100MHz
    .clk_spare                          (clk_spare                 ),// 50MHz
    .sys_rst_n                          (sys_rst_n                 ) 
);

assign cmos_xclk = clk_cmos;
assign cmos_sdat_in = cmos_sdat;
assign cmos_sdat = (cmos_sdat_oe && (cmos_sdat_out == 1'b0)) ? 1'b0 : 1'bz;



// ----------------------------------------------------------------------------------------
// I2C Configuration for SC1336
wire            [   7: 0]      i2c_config_index           ;
wire            [  23: 0]      i2c_config_data            ;
wire            [   7: 0]      i2c_config_size            ;
wire                           i2c_config_done            ;

i2c_wr_16b8b#(
    .CLK_FREQ                           (100_000000                ),//100 MHz
    .I2C_FREQ                           (400_000                   ) //400 KHz(< 400KHz)
)u_i2c_wr_16b8b(
    // global clock
    .clk                                (clk_ctrl                  ),// 100MHz
    .rst_n                              (sys_rst_n                 ),

    // i2c interface     
    .i2c_sclk                           (cmos_sclk                 ),//i2c clock 400KHz
    .i2c_sdat_i                         (cmos_sdat_in              ),
    .i2c_sdat_o                         (cmos_sdat_out             ),
    .i2c_sdat_oe                        (cmos_sdat_oe              ),

    // user interface
    .i2c_config_size                    (i2c_config_size           ),//i2c config data counter
    .i2c_config_index                   (i2c_config_index          ),//i2c config reg index, read 2 reg and write xx reg
    .i2c_config_data                    ({8'h60, i2c_config_data}  ),//i2c config data
    .i2c_config_done                    (i2c_config_done           ) //i2c config timing complete
);

// I2C Configure Data of SC1336
i2c_sc1336_config u_i2c_sc1336_config(
    .LUT_INDEX                          (i2c_config_index          ),
    .LUT_DATA                           (i2c_config_data           ),
    .LUT_SIZE                           (i2c_config_size           ) 
);
                                                            






//****************************************************************************************//
// LCD Driver
wire                           lcd_clk                    ;
assign     lcd_clk      = clk_video    ;

wire            [  11: 0]      lcd_xpos                   ;
wire            [  11: 0]      lcd_ypos                   ;
wire            [  23: 0]      lcd_data                   ;
wire                           lcd_dclk_reg               ;

lcd_driver u_lcd_driver(
    .clk                                (lcd_clk                   ),//720P@60FPS 74.25MHz
    .rst_n                              (sys_rst_n                 ),
    // LCD interface
    .lcd_clk                            (lcd_dclk_reg              ),
    .lcd_blank                          (                          ),
    .lcd_sync                           (                          ),
    .lcd_hs                             (lcd_hs                    ),
    .lcd_vs                             (lcd_vs                    ),
    .lcd_en                             (lcd_de                    ),
    .lcd_rgb                            ({lcd_red, lcd_green, lcd_blue}),

    // User interface
    .lcd_data                           (lcd_data                  ),
    .lcd_request                        (                          ),
    .lcd_xpos                           (lcd_xpos                  ),
    .lcd_ypos                           (lcd_ypos                  ) 
);


// Generate LCD pixel clock using ODDR
ODDR #(
    .DDR_CLK_EDGE                       ("OPPOSITE_EDGE"           ),// "OPPOSITE_EDGE" or "SAME_EDGE" 
    .INIT                               (1'b0                      ),// Initial value of Q: 1'b0 or 1'b1
    .SRTYPE                             ("SYNC"                    ) // Set/Reset type: "SYNC" or "ASYNC" 
) ODDR_inst (
    .Q                                  (lcd_dclk                  ),// 1-bit DDR output
    .C                                  (lcd_dclk_reg              ),// 1-bit clock input
    .CE                                 (1'b1                      ),// 1-bit clock enable input
    .D1                                 (1'b1                      ),// 1-bit data input (positive edge)
    .D2                                 (1'b0                      ),// 1-bit data input (negative edge)
    .R                                  (1'b0                      ),// 1-bit reset
    .S                                  (1'b0                      ) // 1-bit set
);

endmodule